In [2]:
import numpy as np

#### (1) FOR LOOP PRACTICE
- (a.) Create a *list* consisting of the names of my three favorite cities:  Boulder, State College, and Urbana :) 
<br><br>
- (b.) Write a for loop that prints out the name of each of these cities!
<br><br>

*Recall that this could be done as:*
<br>
&emsp;for i in range(3):<br>
&emsp;&emsp;print(list[i])
<br>

where *range(3)* is the iterable object -> but in your lesson, we also talked about another, more Pythonic way to do this where the data itself is the *iterable object*

In [3]:
l = ['Boulder', 'State College', 'Urbana']

In [4]:
for city in l:
    print(city)

Boulder
State College
Urbana


#### (2) WHILE LOOP PRACTICE
- (a.) construct a while loop to sum up the values of 1 through 9, and then print out the sum after the loop is done, as well as the value of i

In [5]:
accum = 0
for i in range(1, 10):
    print(f'i: {i}')
    accum += i
print(f'total: {accum}')
# Answer: 45!

i: 1
i: 2
i: 3
i: 4
i: 5
i: 6
i: 7
i: 8
i: 9
total: 45


#### (3) ARRAY OPERATIONS
- (a.) Convert the temperatures in array d, which are in degrees Fahrenheit, to degrees Celsius, using array operations, and save to a new variable (i.e., *don't overwrite d*)
<br><br>
- (b.) Convert array d to an 1D array and save to a new variable (i.e., *don't overwrite d*)

In [6]:
# Temperatures on a grid on a summer's day 
d = np.array([[100,94,97,92,90,95],[93,87,98,96,93,89]])
print(d)

[[100  94  97  92  90  95]
 [ 93  87  98  96  93  89]]


In [8]:
e = np.copy(d)
e = e-32
e = e/1.80
print(e)

[[37.77777778 34.44444444 36.11111111 33.33333333 32.22222222 35.        ]
 [33.88888889 30.55555556 36.66666667 35.55555556 33.88888889 31.66666667]]


In [11]:
f = np.copy(d).flatten()
print(f)

[100  94  97  92  90  95  93  87  98  96  93  89]


#### (4) ARRAY COMPARISON + LOGICAL OPERATIONS  
- (a.) identify and print only elements in array d that are above 95

100
97
98
96


- (b.) identify and print elements in array d that are above 95 AND are divisble by 2

In [30]:
for num in d[np.where((d>95) & (d%2==0))]:
    print(num)

100
98
96


- (c.) calculate how many elements in d are above 95

In [33]:
print(len(d[np.where(d>95)]))
# Answer: 4 (using array in deg F)

4


- (d.) calculate the mean of all elements in d that are above 95

In [38]:
mean_targets = d[np.where(d>95)]
mean = np.sum(mean_targets) / len(mean_targets)
print(mean)
# Answer: 97.75 (using array in deg F)

97.75
