- import numpy package as alias 'np'

In [3]:
import numpy as np


# Array creation:
*please use NumPy functions rather than doing so manually*
- Create a 1D array, a, that consists of elements 1 through 10 (inclusive)
- Create a 1D array, b, that consists of elements 11 through 20 (inclusive)

In [18]:
a = np.array(np.arange(1, 11, 1))



In [21]:
b = np.array(np.arange(11, 21, 1))

[ 1  2  3  4  5  6  7  8  9 10]
[11 12 13 14 15 16 17 18 19 20]


- Add arrays a and b together and save the result in array c
  - Can use built-in Python operations, although you'll learn more options next week about mathematical operations in NumPy!

In [22]:
c = np.add(a, b)


# Array indexing

In [24]:
# Temperatures on a grid on a summer's day 
d = np.array([[100,94,96,92,90],[95,87,98,96,93]])
print(d)

[[100  94  96  92  90]
 [ 95  87  98  96  93]]


- Access and print the element in the first row, third column of d


In [27]:
print(d[0,3])


92


- Access and print the elements in the second row, and the first through fourth (inclusive) columns of d

In [30]:
print(d[1,0:4])


[95 87 98 96]


# Array Characteristics
- calculate and print the maximum and minimum values in d

In [32]:
print(f'Min: {np.min(d)}\nMax: {np.max(d)}')

Min: 87
Max: 100


- calculate and print the shape of d
- in a comment, describe how many rows and columns d has

In [36]:
print(np.shape(d))


(2, 5)


- calculate the size of d

In [37]:
print(np.size(d))


10


In [ ]:
f